#!/usr/bin/env bash
# governor_context.sh — pull top-K memories for the current scope and write
# them to a markdown file the agent harness will load as context.
#
# Usage:
#   governor_context.sh --target claude|opencode [--scope <path>] [--k 20] [--out <path>]
#
# Exits 0 on empty recall; exits 0 on network error (degrade gracefully).

set -u

TARGET=""
SCOPE=""
K=20
OUT=""
TIMEOUT=2

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target) TARGET="$2"; shift 2 ;;
    --scope)  SCOPE="$2";  shift 2 ;;
    --k)      K="$2";      shift 2 ;;
    --out)    OUT="$2";    shift 2 ;;
    -h|--help)
      sed -n '2,10p' "$0" >&2
      exit 0
      ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$TARGET" ]]; then
  echo "governor_context.sh: --target required" >&2
  exit 2
fi

# Load env from standard locations (first hit wins)
for f in "$HOME/.config/hippocampus.env" "$HOME/.config/sacred-brain.env"; do
  if [[ -r "$f" ]]; then
    set -a; . "$f"; set +a
    break
  fi
done

GOVERNOR_URL="${GOVERNOR_URL:-${HIPPOCAMPUS_URL:-http://127.0.0.1:54323}}"
API_KEY="${GOVERNOR_API_KEY:-${HIPPOCAMPUS_API_KEY:-}}"
USER_ID="${GOVERNOR_USER_ID:-sam}"

PROJECT="$(basename "$PWD")"
SCOPE="${SCOPE:-project:$PROJECT/user:$USER_ID}"

case "$TARGET" in
  claude)   OUT="${OUT:-.claude/CONTEXT_MEMORY.md}" ;;
  opencode) OUT="${OUT:-.agents/CONTEXT_MEMORY.md}" ;;
  *) echo "unknown --target: $TARGET" >&2; exit 2 ;;
esac

mkdir -p "$(dirname "$OUT")"

# Parse scope path into nested Scope JSON via a tiny Python helper.
SCOPE_JSON="$(python3 -c '
import json, sys
path = sys.argv[1]
segs = path.split("/")
scope = None
for kind, sid in reversed([s.split(":", 1) for s in segs]):
    scope = {"kind": kind, "id": sid, "parent": scope}
print(json.dumps(scope))
' "$SCOPE" 2>/dev/null)" || { echo "scope parse failed: $SCOPE" >&2; exit 0; }

REQ_BODY="$(cat <<EOF
{
  "user_id": "$USER_ID",
  "query": "",
  "k": $K,
  "filters": {
    "scope": $SCOPE_JSON,
    "min_confidence": 0.5
  }
}
EOF
)"

HDRS=(-H "Content-Type: application/json")
[[ -n "$API_KEY" ]] && HDRS+=(-H "X-API-Key: $API_KEY")

RESPONSE="$(curl -sS --max-time "$TIMEOUT" "${HDRS[@]}" \
  -X POST "$GOVERNOR_URL/recall" -d "$REQ_BODY" 2>/dev/null)" || {
  # Network failure: leave prior OUT in place
  exit 0
}

# Format results as a markdown bullet list with provenance comments.
FORMATTED="$(printf '%s' "$RESPONSE" | python3 -c '
import json, sys
try:
    data = json.loads(sys.stdin.read() or "{}")
except Exception:
    sys.exit(0)
results = data.get("results") or []
print("<!-- generated by governor_context.sh; scope='"$SCOPE"' -->")
print("# Relevant memory")
print()
if not results:
    print("_(no memories for this scope yet)_")
else:
    for r in results:
        text = (r.get("text") or "").strip().replace("\n", " ")
        kind = r.get("kind") or "?"
        conf = r.get("confidence")
        conf_str = f"{conf:.2f}" if isinstance(conf, (int, float)) else "?"
        disputed = " ⚠disputed" if r.get("disputed") else ""
        src = (r.get("provenance") or {}).get("source") or "?"
        print(f"- {text}  \n  <!-- kind={kind} conf={conf_str} src={src}{disputed} -->")
' 2>/dev/null)" || exit 0

printf '%s\n' "$FORMATTED" > "$OUT"
exit 0
